### ISSUE TITLE
AssertionError: Non-OK status code while retrieving get_finished_torrents: 404

### ISSUE THREAD

**Issue by herouxb** [Rudd-O/seedboxtools#5]
Hi, i always have this error 

AssertionError: Non-OK status code while retrieving get_finished_torrents: 404

Complete output is:
$ bin/leechtorrents   
Starting download of finished torrents
Traceback (most recent call last):
  File "bin/leechtorrents", line 10, in <module>
    sys.exit(mainloop())
  File "/xyz/seedboxtools-1.2.11/src/seedboxtools/leecher.py", line 167, in mainloop
    retvalue = do_guarded()
  File "/xyz/seedboxtools-1.2.11/src/seedboxtools/leecher.py", line 151, in do_guarded
    remove_finished=opts.remove_finished
  File "/xyz/seedboxtools-1.2.11/src/seedboxtools/leecher.py", line 12, in download
    for torrent, status, filename in client.get_files_to_download():
  File "/xyz/seedboxtools-1.2.11/src/seedboxtools/clients.py", line 45, in get_files_to_download
    torrents = self.get_finished_torrents()
  File "/xyz/seedboxtools-1.2.11/src/seedboxtools/clients.py", line 241, in get_finished_torrents
    assert r.status_code == 200, "Non-OK status code while retrieving get_finished_torrents: %r"%r.status_code
AssertionError: Non-OK status code while retrieving get_finished_torrents: 404

Do you have any ideas ?

thanks,

**Comment by Rudd-O** [comment]
I am speculatively closing this issue presuming that this was fixed a few months ago.  Please reopen if you feel that the problem was not solved.
